# app/api/routes/exporter.py
# Purpose: APIRouter for exporting workspace transcripts, study notes, and sources summary.

from fastapi import APIRouter, HTTPException, Path, Query
from fastapi.responses import Response
import logging
import json

from app.core.config import settings
from app.core.database import get_chat_history
from app.api.routes.sources import load_sources

logger = logging.getLogger("kivo.exporter")
router = APIRouter()


@router.get("/{workspace_id}/export")
def export_workspace_transcript(
    workspace_id: str = Path(
        ..., pattern=r"^[0-9a-f-]{36}$", description="The workspace ID"
    ),
    format: str = Query("markdown", description="Export format: 'markdown' or 'html'"),
):
    """
    Exports workspace chat transcript, sources summary, and metadata as a downloadable file.
    """
    workspace_dir = settings.workspaces_dir / workspace_id
    if not workspace_dir.exists():
        raise HTTPException(status_code=404, detail="Workspace not found")

    ws_name = "Workspace"
    meta_file = workspace_dir / "metadata.json"
    if meta_file.exists():
        try:
            with open(meta_file, "r") as f:
                meta = json.load(f)
                ws_name = meta.get("name", "Workspace")
        except Exception:
            pass

    sources = load_sources(workspace_id)
    history = get_chat_history(workspace_id)

    # Build Markdown document
    lines = [
        f"# {ws_name} — Workspace Report & Chat Transcript",
        f"**Generated by Kivo Workspace Edge AI Platform**\n",
        "---",
        "## 📚 Workspace Sources",
    ]

    if not sources:
        lines.append("*No sources uploaded to this workspace yet.*\n")
    else:
        for s in sources:
            lines.append(f"- **{s.name}** ({s.type.upper()}) — Status: {s.status}")

    lines.append("\n---")
    lines.append("## 💬 Chat Transcript & Q&A History\n")

    if not history:
        lines.append("*No chat messages recorded in this workspace yet.*\n")
    else:
        for msg in history:
            role = "👤 **User**" if msg["role"] == "user" else "🤖 **Kivo AI**"
            mode = f" *(Mode: {msg.get('mode', 'default')})*" if msg["role"] == "user" else ""
            lines.append(f"### {role}{mode}")
            lines.append(f"{msg['content']}\n")

            if msg.get("citations"):
                lines.append("**Sources Used:**")
                for c in msg["citations"]:
                    s_name = c.get("source_name", "Document")
                    pages = c.get("pages", [])
                    page_str = f" (p. {', '.join(map(str, pages))})" if pages else ""
                    lines.append(f"- `{s_name}`{page_str}")
                lines.append("")

    content_str = "\n".join(lines)
    file_name = f"{ws_name.lower().replace(' ', '_')}_export.md"

    return Response(
        content=content_str,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{file_name}"'},
    )
