// features/onboarding/models/onboarding_state.dart
// Purpose: Models representing stages, model registry, and progress for Kivo Workspace onboarding.

enum OnboardingStage {
  welcome,
  modelSelection,
  summary,
  downloading,
  customization,
  done,
}

class CuratedModel {
  final String id;
  final String name;
  final String category;
  final String capability;
  final String size;
  final double sizeGb;
  final String ram;
  final int ramGb;
  final String compatibility;
  final String description;

  const CuratedModel({
    required this.id,
    required this.name,
    required this.category,
    required this.capability,
    required this.size,
    required this.sizeGb,
    required this.ram,
    required this.ramGb,
    required this.compatibility,
    required this.description,
  });

  bool matchesSystemSpecs({required int systemRamGb, required bool hasHardwareAcceleration}) {
    if (systemRamGb < ramGb) return false;
    if (compatibility.contains('High-end') && !hasHardwareAcceleration) return false;
    return true;
  }
}

class OnboardingProgress {
  final OnboardingStage activeStage;
  final List<String> selectedModelIds;
  final double downloadSpeed; // MB/s (real-time, from actual pull)
  final String downloadEta;  // Calculated from sliding avg speed
  final double downloadProgress; // 0.0 to 1.0
  final double downloadedMb;
  final double totalMb;
  final String? errorMessage;
  final bool isInternetConnected;
  final Map<String, String> installStatus; // modelId -> status string
  final bool isOllamaInstalled;
  final List<String> installedOllamaModels;
  final bool isDownloading;
  final bool downloadCancelled;

  OnboardingProgress({
    this.activeStage = OnboardingStage.welcome,
    this.selectedModelIds = const ['qwen2.5:1.5b'],
    this.downloadSpeed = 0.0,
    this.downloadEta = 'Calculating...',
    this.downloadProgress = 0.0,
    this.downloadedMb = 0.0,
    this.totalMb = 0.0,
    this.errorMessage,
    this.isInternetConnected = true,
    this.installStatus = const {},
    this.isOllamaInstalled = false,
    this.installedOllamaModels = const [],
    this.isDownloading = false,
    this.downloadCancelled = false,
  });

  OnboardingProgress copyWith({
    OnboardingStage? activeStage,
    List<String>? selectedModelIds,
    double? downloadSpeed,
    String? downloadEta,
    double? downloadProgress,
    double? downloadedMb,
    double? totalMb,
    String? errorMessage,
    bool? isInternetConnected,
    Map<String, String>? installStatus,
    bool? isOllamaInstalled,
    List<String>? installedOllamaModels,
    bool? isDownloading,
    bool? downloadCancelled,
  }) {
    return OnboardingProgress(
      activeStage: activeStage ?? this.activeStage,
      selectedModelIds: selectedModelIds ?? this.selectedModelIds,
      downloadSpeed: downloadSpeed ?? this.downloadSpeed,
      downloadEta: downloadEta ?? this.downloadEta,
      downloadProgress: downloadProgress ?? this.downloadProgress,
      downloadedMb: downloadedMb ?? this.downloadedMb,
      totalMb: totalMb ?? this.totalMb,
      errorMessage: errorMessage,
      isInternetConnected: isInternetConnected ?? this.isInternetConnected,
      installStatus: installStatus ?? this.installStatus,
      isOllamaInstalled: isOllamaInstalled ?? this.isOllamaInstalled,
      installedOllamaModels: installedOllamaModels ?? this.installedOllamaModels,
      isDownloading: isDownloading ?? this.isDownloading,
      downloadCancelled: downloadCancelled ?? this.downloadCancelled,
    );
  }
}

// Curated Model Registry containing >= 4 models per category across 15 categories.
final List<CuratedModel> curatedModelRegistry = [
  // --- Reasoning & Logic ---
  const CuratedModel(
    id: 'deepseek-r1:1.5b',
    name: 'DeepSeek R1 1.5B',
    category: 'Reasoning & Logic',
    capability: 'Reasoning & Logic',
    size: '1.1 GB',
    sizeGb: 1.1,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Advanced reasoning and mathematical logic in a lightweight parameter footprint.',
  ),
  const CuratedModel(
    id: 'qwen2.5-math:1.5b',
    name: 'Qwen 2.5 Math 1.5B',
    category: 'Reasoning & Logic',
    capability: 'Lightweight Math',
    size: '980 MB',
    sizeGb: 0.98,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Lightweight mathematical reasoning model.',
  ),
  const CuratedModel(
    id: 'qwen2.5-math:7b',
    name: 'Qwen 2.5 Math 7B',
    category: 'Reasoning & Logic',
    capability: 'Mathematical Synthesis',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-to-High end devices',
    description: 'Specially trained for multi-step math problems, equations, and mathematical retrieval.',
  ),
  const CuratedModel(
    id: 'marco-o1:latest',
    name: 'Marco-O1 7B',
    category: 'Reasoning & Logic',
    capability: 'Logical Search Reasoning',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-to-High end devices',
    description: 'Open reasoning model optimized for search and translation reasoning.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:8b',
    name: 'DeepSeek R1 8B',
    category: 'Reasoning & Logic',
    capability: 'Deep Reasoning',
    size: '4.9 GB',
    sizeGb: 4.9,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Implements reinforcement learning reasoning. Exceptional at math, logic, and coding QA.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:14b',
    name: 'DeepSeek R1 14B',
    category: 'Reasoning & Logic',
    capability: 'Expert Reasoning',
    size: '9.0 GB',
    sizeGb: 9.0,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end GPUs / M-Series Macs',
    description: 'High-intellect reasoning engine for complex synthesis and logical deep dives.',
  ),

  // --- General Chat & Assistant ---
  const CuratedModel(
    id: 'qwen2.5:1.5b',
    name: 'Qwen 2.5 1.5B (Default)',
    category: 'General Chat & Assistant',
    capability: 'Balanced Chat',
    size: '980 MB',
    sizeGb: 0.98,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Fast, highly reliable conversational model. Excels at context-grounded retrieval QA.',
  ),
  const CuratedModel(
    id: 'smollm2:1.7b',
    name: 'SmolLM2 1.7B',
    category: 'General Chat & Assistant',
    capability: 'Fast General Conversationalist',
    size: '1.7 GB',
    sizeGb: 1.7,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Ultra-small general conversational model.',
  ),
  const CuratedModel(
    id: 'llama3.2:3b',
    name: 'Llama 3.2 3B',
    category: 'General Chat & Assistant',
    capability: 'Conversational Quality',
    size: '2.0 GB',
    sizeGb: 2.0,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Meta\'s highly capable small conversational assistant. Excellent vocabulary and flow.',
  ),
  const CuratedModel(
    id: 'gemma2:2b',
    name: 'Gemma 2 2B',
    category: 'General Chat & Assistant',
    capability: 'Small General Chat',
    size: '1.6 GB',
    sizeGb: 1.6,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Google\'s 2B model which punches far above its weight class in general chat.',
  ),
  const CuratedModel(
    id: 'llama3.1:8b',
    name: 'Llama 3.1 8B',
    category: 'General Chat & Assistant',
    capability: 'Balanced Generalist',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Standard industry benchmark for 8B chat and general language tasks.',
  ),
  const CuratedModel(
    id: 'gemma2:9b',
    name: 'Gemma 2 9B',
    category: 'General Chat & Assistant',
    capability: 'Instruction Following',
    size: '5.5 GB',
    sizeGb: 5.5,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end devices',
    description: 'Google\'s high-capacity open model. Excellent structural comprehension and detail.',
  ),

  // --- Coding & Technical ---
  const CuratedModel(
    id: 'qwen2.5-coder:1.5b',
    name: 'Qwen 2.5 Coder 1.5B',
    category: 'Coding & Technical',
    capability: 'Fast Coding',
    size: '980 MB',
    sizeGb: 0.98,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Optimized for code suggestions, autocomplete, and syntax assistance on lower-spec hardware.',
  ),
  const CuratedModel(
    id: 'granite-code:3b',
    name: 'Granite Code 3B',
    category: 'Coding & Technical',
    capability: 'Lightweight Code Assistant',
    size: '2.0 GB',
    sizeGb: 2.0,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'IBM\'s granite coding model, optimized for code assistant tasks.',
  ),
  const CuratedModel(
    id: 'qwen2.5-coder:7b',
    name: 'Qwen 2.5 Coder 7B',
    category: 'Coding & Technical',
    capability: 'Full Code Generation',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-to-High end devices',
    description: 'State-of-the-art coding assistant. Comparable to much larger models in programming tests.',
  ),
  const CuratedModel(
    id: 'codellama:7b',
    name: 'CodeLlama 7B',
    category: 'Coding & Technical',
    capability: 'Coding Assistant',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Meta\'s specialized coder model. High accuracy on python, C++, and javascript.',
  ),
  const CuratedModel(
    id: 'codellama:13b',
    name: 'CodeLlama 13B',
    category: 'Coding & Technical',
    capability: 'Heavy Code Synthesis',
    size: '7.3 GB',
    sizeGb: 7.3,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'High-end devices',
    description: 'Larger coder capacity. Handles longer program context and complex software architecture.',
  ),
  const CuratedModel(
    id: 'qwen2.5-coder:14b',
    name: 'Qwen 2.5 Coder 14B',
    category: 'Coding & Technical',
    capability: 'Expert Coding Loops',
    size: '9.0 GB',
    sizeGb: 9.0,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end GPUs / M-Series Macs',
    description: 'Advanced code intelligence engine for complex synthesis and logical coding loops.',
  ),

  // --- Creative & Narrative ---
  const CuratedModel(
    id: 'llama3.2:1b',
    name: 'Llama 3.2 1B (Creative)',
    category: 'Creative & Narrative',
    capability: 'Fast Creative Prose',
    size: '1.3 GB',
    sizeGb: 1.3,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Meta\'s smallest Llama model, ideal for fast creative writing on CPU.',
  ),
  const CuratedModel(
    id: 'smollm:360m',
    name: 'SmolLM 360M (Creative)',
    category: 'Creative & Narrative',
    capability: 'Compact Creative Writing',
    size: '360 MB',
    sizeGb: 0.36,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Ultra-compact model, great for quick creative prompts.',
  ),
  const CuratedModel(
    id: 'mistral:latest',
    name: 'Mistral 7B',
    category: 'Creative & Narrative',
    capability: 'Narrative Flow',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'A classic favorite for narrative prose, storytelling, and high-entropy text generation.',
  ),
  const CuratedModel(
    id: 'llama3:8b',
    name: 'Llama 3 8B Instruct',
    category: 'Creative & Narrative',
    capability: 'Expressive Style',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-to-High end devices',
    description: 'Immersive, highly expressive chatbot tuning of the Meta Llama 3 architecture.',
  ),
  const CuratedModel(
    id: 'hermes3:8b',
    name: 'Hermes 3 8B',
    category: 'Creative & Narrative',
    capability: 'Unbound Creative Writing',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Nous Research flag model. Highly customizable, creative, and immersive narrative styling.',
  ),
  const CuratedModel(
    id: 'solar:latest',
    name: 'Solar 10.7B',
    category: 'Creative & Narrative',
    capability: 'Immersive Storytelling',
    size: '6.1 GB',
    sizeGb: 6.1,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end devices',
    description: 'Compact 10.7B parameter model, excellent for creative storytelling.',
  ),

  // --- Educational & Information ---
  const CuratedModel(
    id: 'phi3:latest',
    name: 'Phi-3 3.8B',
    category: 'Educational & Information',
    capability: 'Logical Explanation',
    size: '2.2 GB',
    sizeGb: 2.2,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Microsoft\'s high-reasoning small model. Excellent for conceptual teaching and summaries.',
  ),
  const CuratedModel(
    id: 'orca-mini:3b',
    name: 'Orca Mini 3B',
    category: 'Educational & Information',
    capability: 'Fact Explanation',
    size: '2.0 GB',
    sizeGb: 2.0,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Small conversational assistant optimized for factual accuracy and instruction following.',
  ),
  const CuratedModel(
    id: 'phi3.5:latest',
    name: 'Phi-3.5 3.8B',
    category: 'Educational & Information',
    capability: 'Teaching Assistant',
    size: '2.2 GB',
    sizeGb: 2.2,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Updated Microsoft model with strong reasoning, instruction following, and teaching capability.',
  ),
  const CuratedModel(
    id: 'qwen2.5:3b',
    name: 'Qwen 2.5 3B',
    category: 'Educational & Information',
    capability: 'Fast Retrieval & Tutoring',
    size: '1.9 GB',
    sizeGb: 1.9,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Intermediate Qwen size. Combines reasoning capabilities with fast CPU speeds.',
  ),
  const CuratedModel(
    id: 'openhermes:latest',
    name: 'OpenHermes 7B',
    category: 'Educational & Information',
    capability: 'Educational QA',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-end devices',
    description: '7B model trained on high-quality educational datasets.',
  ),
  const CuratedModel(
    id: 'phi3:medium',
    name: 'Phi-3 Medium 14B',
    category: 'Educational & Information',
    capability: 'Deep Explanations',
    size: '7.9 GB',
    sizeGb: 7.9,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end devices',
    description: 'Larger Microsoft model with deep textbook-like logic. Great for multi-domain tutoring.',
  ),

  // --- Medical & Science ---
  const CuratedModel(
    id: 'biogpt:latest',
    name: 'BioGPT 1.5B',
    category: 'Medical & Science',
    capability: 'Biological Extraction',
    size: '1.2 GB',
    sizeGb: 1.2,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Trained on PubMed literature. Exceptional at biomedical name extraction and science QA.',
  ),
  const CuratedModel(
    id: 'bespoke-minichemp:latest',
    name: 'Bespoke Minichem 1.5B',
    category: 'Medical & Science',
    capability: 'Chemistry Assistant',
    size: '1.5 GB',
    sizeGb: 1.5,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Specially tuned small chemistry and science model.',
  ),
  const CuratedModel(
    id: 'medllama2:7b',
    name: 'MedLlama 2 7B',
    category: 'Medical & Science',
    capability: 'Clinical QA',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Llama 2 model fine-tuned on medical journals, clinical QA datasets, and terminologies.',
  ),
  const CuratedModel(
    id: 'meditron:7b',
    name: 'Meditron 7B',
    category: 'Medical & Science',
    capability: 'Clinical Diagnostics Support',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'EPFL open-source medical model trained extensively on clinical practice guidelines.',
  ),
  const CuratedModel(
    id: 'clinical-llama2:latest',
    name: 'Clinical-Llama 2 7B',
    category: 'Medical & Science',
    capability: 'Clinical Summaries',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-end devices',
    description: 'Optimized for parsing doctor notes, clinical charts, and medical document summaries.',
  ),
  const CuratedModel(
    id: 'meditron:70b',
    name: 'Meditron 70B',
    category: 'Medical & Science',
    capability: 'Expert Medical QA',
    size: '40.0 GB',
    sizeGb: 40.0,
    ram: '96 GB+',
    ramGb: 96,
    compatibility: 'Server GPUs / 128GB Unified RAM',
    description: 'EPFL\'s 70B parameter medical model for expert medical QA.',
  ),

  // --- Multilingual & Translation ---
  const CuratedModel(
    id: 'gemma:2b',
    name: 'Gemma 2B Multilingual',
    category: 'Multilingual & Translation',
    capability: 'Lightweight Multilingual',
    size: '1.6 GB',
    sizeGb: 1.6,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Google\'s 2B parameter model, excellent at language tasks.',
  ),
  const CuratedModel(
    id: 'yi:latest',
    name: 'Yi 6B',
    category: 'Multilingual & Translation',
    capability: 'Bilingual Assistant',
    size: '3.5 GB',
    sizeGb: 3.5,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Bilingual model by 01.AI, excellent at English and Chinese.',
  ),
  const CuratedModel(
    id: 'aya:8b',
    name: 'Aya 23 8B',
    category: 'Multilingual & Translation',
    capability: 'Multilingual Translation',
    size: '4.8 GB',
    sizeGb: 4.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-to-High end devices',
    description: 'Cohere\'s flagship multilingual model covering 23 different languages with high accuracy.',
  ),
  const CuratedModel(
    id: 'qwen2.5:7b',
    name: 'Qwen 2.5 7B',
    category: 'Multilingual & Translation',
    capability: 'Global Languages',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-to-High end devices',
    description: 'Outstanding performance across Asian, European, and Middle Eastern languages.',
  ),
  const CuratedModel(
    id: 'aya:35b',
    name: 'Aya 35B',
    category: 'Multilingual & Translation',
    capability: 'Heavy Translation',
    size: '20.0 GB',
    sizeGb: 20.0,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'High-end devices',
    description: 'Cohere\'s 35B model, expert in multilingual translation across 101 languages.',
  ),
  const CuratedModel(
    id: 'command-r:latest',
    name: 'Command R 35B',
    category: 'Multilingual & Translation',
    capability: 'Expert Localization',
    size: '20.0 GB',
    sizeGb: 20.0,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'Super-High/Workstation specs',
    description: 'Large-scale multilingual model. Excels at enterprise-level localization and translation.',
  ),

  // --- Speed & Low-Resource ---
  const CuratedModel(
    id: 'qwen2.5:0.5b',
    name: 'Qwen 2.5 0.5B',
    category: 'Speed & Low-Resource',
    capability: 'Ultra-lightweight',
    size: '390 MB',
    sizeGb: 0.39,
    ram: '2 GB+',
    ramGb: 2,
    compatibility: 'All devices',
    description: 'Smallest Qwen model. Near-instantaneous response times, ideal for micro-servers.',
  ),
  const CuratedModel(
    id: 'tinyllama:latest',
    name: 'TinyLlama 1.1B',
    category: 'Speed & Low-Resource',
    capability: 'Fast CPU Chat',
    size: '637 MB',
    sizeGb: 0.63,
    ram: '2 GB+',
    ramGb: 2,
    compatibility: 'All devices',
    description: 'Compact 1B parameter model optimized for speed and local CPU inference.',
  ),
  const CuratedModel(
    id: 'smollm2:135m',
    name: 'SmolLM2 135M',
    category: 'Speed & Low-Resource',
    capability: 'Ultra-lightweight 135M',
    size: '130 MB',
    sizeGb: 0.13,
    ram: '2 GB+',
    ramGb: 2,
    compatibility: 'All devices',
    description: 'Super lightweight 135M assistant.',
  ),
  const CuratedModel(
    id: 'smollm2:360m',
    name: 'SmolLM2 360M',
    category: 'Speed & Low-Resource',
    capability: 'Lightweight 360M',
    size: '360 MB',
    sizeGb: 0.36,
    ram: '2 GB+',
    ramGb: 2,
    compatibility: 'All devices',
    description: 'Super lightweight 360M assistant.',
  ),
  const CuratedModel(
    id: 'stablelm2:latest',
    name: 'StableLM 2 1.6B',
    category: 'Speed & Low-Resource',
    capability: 'Speed Optimized',
    size: '1.6 GB',
    sizeGb: 1.6,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Stability AI\'s 1.6B parameter model optimized for speed.',
  ),
  const CuratedModel(
    id: 'falcon2:latest',
    name: 'Falcon 2 11B',
    category: 'Speed & Low-Resource',
    capability: 'Fast CPU Inference',
    size: '5.5 GB',
    sizeGb: 5.5,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Falcon 11B parameter model optimized for fast CPU inference.',
  ),

  // --- High-Capacity Reasoners ---
  const CuratedModel(
    id: 'deepseek-r1:32b',
    name: 'DeepSeek R1 32B',
    category: 'High-Capacity Reasoners',
    capability: 'Professional Reasoning',
    size: '20.0 GB',
    sizeGb: 20.0,
    ram: '32 GB+',
    ramGb: 32,
    compatibility: 'High-end workstation GPU / Mac Studio',
    description: 'Professional reasoning capacity for multi-document comparisons and logic audits.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:70b',
    name: 'DeepSeek R1 70B',
    category: 'High-Capacity Reasoners',
    capability: 'Extreme Reasoning',
    size: '42.0 GB',
    sizeGb: 42.0,
    ram: '64 GB+',
    ramGb: 64,
    compatibility: 'Server GPUs / 128GB Unified RAM',
    description: 'State-of-the-art open reasoning model. Bypasses GPT-4o in mathematical benchmarks.',
  ),
  const CuratedModel(
    id: 'qwen2.5:72b',
    name: 'Qwen 2.5 72B',
    category: 'High-Capacity Reasoners',
    capability: 'Full Generalist Intelligence',
    size: '47.0 GB',
    sizeGb: 47.0,
    ram: '64 GB+',
    ramGb: 64,
    compatibility: 'Server GPUs / 128GB Unified RAM',
    description: 'Flagship Qwen model. Extreme knowledge density across coding, science, and languages.',
  ),
  const CuratedModel(
    id: 'llama3.1:70b',
    name: 'Llama 3.1 70B',
    category: 'High-Capacity Reasoners',
    capability: 'High Capacity Generalist',
    size: '40.0 GB',
    sizeGb: 40.0,
    ram: '64 GB+',
    ramGb: 64,
    compatibility: 'Server GPUs / 128GB Unified RAM',
    description: 'Standard high-capacity Llama model for enterprise and research tasks.',
  ),
  const CuratedModel(
    id: 'llama3.3:70b',
    name: 'Llama 3.3 70B',
    category: 'High-Capacity Reasoners',
    capability: 'Refined High Capacity',
    size: '42.0 GB',
    sizeGb: 42.0,
    ram: '64 GB+',
    ramGb: 64,
    compatibility: 'Server GPUs / 128GB Unified RAM',
    description: 'Meta\'s latest 70B model with improved reasoning capabilities.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:671b',
    name: 'DeepSeek R1 671B',
    category: 'High-Capacity Reasoners',
    capability: 'Supercomputer Scale Intelligence',
    size: '400 GB',
    sizeGb: 400.0,
    ram: '512 GB+',
    ramGb: 512,
    compatibility: 'Multi-node server setups',
    description: 'The largest DeepSeek R1 model, requiring multi-node setups or large workstations.',
  ),

  // --- Agentic & Tool-Use ---
  const CuratedModel(
    id: 'llama3-groq-tool-use:8b',
    name: 'Llama 3 Groq Tool Use 8B',
    category: 'Agentic & Tool-Use',
    capability: 'JSON & Tool Calling',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-to-High end devices',
    description: 'Groq-optimized Llama 3 model designed specifically to output clean JSON schemas and arguments.',
  ),
  const CuratedModel(
    id: 'granite-code:8b',
    name: 'Granite Code 8B',
    category: 'Agentic & Tool-Use',
    capability: 'Code Tool Calling',
    size: '5.0 GB',
    sizeGb: 5.0,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'IBM\'s Granite code model, optimized for code tool calling.',
  ),
  const CuratedModel(
    id: 'nous-hermes2:latest',
    name: 'Nous Hermes 2 7B',
    category: 'Agentic & Tool-Use',
    capability: 'Tool Utilization',
    size: '4.0 GB',
    sizeGb: 4.0,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Hermes 2 7B model optimized for tool utilization.',
  ),
  const CuratedModel(
    id: 'mistral-nemo:latest',
    name: 'Mistral Nemo 12B',
    category: 'Agentic & Tool-Use',
    capability: 'Function Calling',
    size: '7.1 GB',
    sizeGb: 7.1,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Mistral 12B model, excellent at function calling and structured outputs.',
  ),
  const CuratedModel(
    id: 'command-r-plus:latest',
    name: 'Command R+ 104B',
    category: 'Agentic & Tool-Use',
    capability: 'Enterprise Tool Use',
    size: '59.0 GB',
    sizeGb: 59.0,
    ram: '96 GB+',
    ramGb: 96,
    compatibility: 'Super-High specs',
    description: 'Cohere\'s flagship agentic model, highly optimized for tool calling.',
  ),
  const CuratedModel(
    id: 'qwen2.5:14b',
    name: 'Qwen 2.5 14B (Agentic)',
    category: 'Agentic & Tool-Use',
    capability: 'Autonomous Agent Loops',
    size: '9.0 GB',
    sizeGb: 9.0,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end GPUs',
    description: 'Qwen 2.5 14B instruction tuned model, highly capable in agent loops.',
  ),

  // --- Roleplay & Storytelling ---
  const CuratedModel(
    id: 'mythomax:latest',
    name: 'MythoMax 13B',
    category: 'Roleplay & Storytelling',
    capability: 'Immersive Prose',
    size: '7.4 GB',
    sizeGb: 7.4,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'High-end devices',
    description: 'A custom merge of Llama models optimized for roleplay, dialogue, and creative stories.',
  ),
  const CuratedModel(
    id: 'fimbulvetr:latest',
    name: 'Fimbulvetr 8B',
    category: 'Roleplay & Storytelling',
    capability: 'Immersive Storytelling',
    size: '6.0 GB',
    sizeGb: 6.0,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Llama 3 8B fine-tune optimized for immersive storytelling and roleplay.',
  ),
  const CuratedModel(
    id: 'wizardlm:latest',
    name: 'WizardLM 7B',
    category: 'Roleplay & Storytelling',
    capability: 'Character Interactions',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Classic instruction-following model, excellent for character interactions.',
  ),
  const CuratedModel(
    id: 'gemma2:27b',
    name: 'Gemma 2 27B',
    category: 'Roleplay & Storytelling',
    capability: 'Creative Text Vocabulary',
    size: '16.0 GB',
    sizeGb: 16.0,
    ram: '48 GB+',
    ramGb: 48,
    compatibility: 'High-spec workstation specs',
    description: 'Google\'s 27B model, superb vocabulary and creative text structure.',
  ),
  const CuratedModel(
    id: 'mixtral:8x7b',
    name: 'Mixtral 8x7B',
    category: 'Roleplay & Storytelling',
    capability: 'Complex Narrations',
    size: '26.0 GB',
    sizeGb: 26.0,
    ram: '48 GB+',
    ramGb: 48,
    compatibility: 'High-end devices',
    description: 'High-capacity Mixture-of-Experts model, expert at complex narrations.',
  ),
  const CuratedModel(
    id: 'mixtral:8x22b',
    name: 'Mixtral 8x22B',
    category: 'Roleplay & Storytelling',
    capability: 'Expert Story Generation',
    size: '81.0 GB',
    sizeGb: 81.0,
    ram: '96 GB+',
    ramGb: 96,
    compatibility: 'Server setups',
    description: 'Mixtral 8x22B model for expert story generation.',
  ),

  // --- Summarization ---
  const CuratedModel(
    id: 'minicpm:latest',
    name: 'MiniCPM 2B',
    category: 'Summarization',
    capability: 'Deep Summarization',
    size: '1.8 GB',
    sizeGb: 1.8,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Compact general model with deep context summarization capabilities.',
  ),
  const CuratedModel(
    id: 'snorky:latest',
    name: 'Snorky 3B',
    category: 'Summarization',
    capability: 'Document Parsing',
    size: '2.0 GB',
    sizeGb: 2.0,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Tuned lightweight model for document parsing.',
  ),
  const CuratedModel(
    id: 'gemma:7b',
    name: 'Gemma 7B (Summary)',
    category: 'Summarization',
    capability: 'Concise Summaries',
    size: '4.8 GB',
    sizeGb: 4.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Gemma 7B model, excellent at concise summaries.',
  ),
  const CuratedModel(
    id: 'neural-chat:latest',
    name: 'Neural Chat 7B',
    category: 'Summarization',
    capability: 'Bullet Summaries',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Intel\'s fine-tune on 7B, great for summaries.',
  ),
  const CuratedModel(
    id: 'vicuna:latest',
    name: 'Vicuna 7B',
    category: 'Summarization',
    capability: 'Instruction Summaries',
    size: '4.4 GB',
    sizeGb: 4.4,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Vicuna 7B model, classic instruction-following summarizer.',
  ),
  const CuratedModel(
    id: 'llama2:latest',
    name: 'Llama 2 7B',
    category: 'Summarization',
    capability: 'Structural Summaries',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Standard Llama 2 7B model for structural summaries.',
  ),

  // --- Custom (Ollama tag loader) ---
  const CuratedModel(
    id: 'mistral:7b',
    name: 'Mistral 7B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'User defined',
    description: 'Pulls the standard 7B Mistral model from the Ollama library.',
  ),
  const CuratedModel(
    id: 'codegemma:2b',
    name: 'CodeGemma 2B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '1.6 GB',
    sizeGb: 1.6,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'User defined',
    description: 'Pulls the lightweight coding model by Google from the Ollama library.',
  ),
  const CuratedModel(
    id: 'stable-beluga:7b',
    name: 'Stable Beluga 7B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'User defined',
    description: 'Pulls Stability AI\'s fine-tuned assistant from the Ollama library.',
  ),
  const CuratedModel(
    id: 'llama2:13b',
    name: 'Llama 2 13B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '7.4 GB',
    sizeGb: 7.4,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'User defined',
    description: 'Pulls Meta\'s classic 13B Llama 2 model from the Ollama library.',
  ),
  const CuratedModel(
    id: 'codegemma:7b',
    name: 'CodeGemma 7B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '4.8 GB',
    sizeGb: 4.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'User defined',
    description: 'Pulls Google\'s 7B code specialist model from the Ollama library.',
  ),
  const CuratedModel(
    id: 'stable-beluga:13b',
    name: 'Stable Beluga 13B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '7.4 GB',
    sizeGb: 7.4,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'User defined',
    description: 'Pulls Stability AI\'s 13B model from the Ollama library.',
  ),

  // --- Uncensored ---
  const CuratedModel(
    id: 'dolphin-mistral:latest',
    name: 'Dolphin Mistral 7B',
    category: 'Uncensored',
    capability: 'Uncensored General Assistant',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Mistral 7B tuned by Eric Hartford. Standard uncensored assistant, highly direct.',
  ),
  const CuratedModel(
    id: 'dolphin-llama3:8b',
    name: 'Dolphin Llama 3 8B',
    category: 'Uncensored',
    capability: 'Uncensored Llama Assistant',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Llama 3 8B uncensored. High conversational density without alignment filters.',
  ),
  const CuratedModel(
    id: 'wizard-vicuna-uncensored:13b',
    name: 'Wizard Vicuna 13B Uncensored',
    category: 'Uncensored',
    capability: 'Uncensored Complex QA',
    size: '7.4 GB',
    sizeGb: 7.4,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'High-end devices',
    description: 'A classic large uncensored model. Good for detailed queries in unfiltered domains.',
  ),
  const CuratedModel(
    id: 'dolphin-phi3:latest',
    name: 'Dolphin Phi-3 3.8B',
    category: 'Uncensored',
    capability: 'Uncensored Logical Assistant',
    size: '2.2 GB',
    sizeGb: 2.2,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Uncensored variant of Microsoft\'s Phi-3 model. Strong logic in a small package.',
  ),
  const CuratedModel(
    id: 'dolphin-phi:latest',
    name: 'Dolphin Phi-2 2.7B',
    category: 'Uncensored',
    capability: 'Fast Uncensored Assistant',
    size: '1.6 GB',
    sizeGb: 1.6,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Uncensored variant of Microsoft\'s Phi-2 model, fast and direct.',
  ),
  const CuratedModel(
    id: 'dolphin-mixtral:latest',
    name: 'Dolphin Mixtral 8x7B',
    category: 'Uncensored',
    capability: 'Expert Uncensored Assistant',
    size: '26.0 GB',
    sizeGb: 26.0,
    ram: '48 GB+',
    ramGb: 48,
    compatibility: 'High-end specs',
    description: 'Uncensored Mixture of Experts model, highly creative with no safety filters.',
  ),
];
